name: Testes de funcionalidades após alterações de código

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configura o Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Instala os requisitos do módulo
      run: |
        python -m pip install -r requirements.txt
    - name: Executa os testes do pacote
      run: |
        python -m pytest
    - name: Veriricações de qualidade de código - tipagem estática
      run: |
        python -m mypy .
    - name: Verificações de qualidade de código - linter PEP8
      run: |
        python -m flake8 .
